name: ScopeSignal by ScopeLP

on:
  schedule:
    # Runs at 7:00 AM EST daily (12:00 UTC), weekdays only
    - cron: '0 12 * * 1-5'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  send-scopelp-newsbrief:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests beautifulsoup4 schedule lxml

    - name: Send ScopeSignal Newsletter
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        GITHUB_ACTIONS: true
      run: |
        python financial_newsletter.py

